# Kısayollar
bindsym $mod+Return exec kitty
bindsym $mod+d exec rofi -show drun
bindsym $mod+b exec librewolf
bindsym $mod+e exec kitty --title yazi yazi
bindsym $mod+c exec kitty --title nvim nvim
bindsym $mod+v exec copyq show
bindsym $mod+Shift+v exec blueman-manager
bindsym $mod+z exec localsend
bindsym $mod+Shift+d exec discord
bindsym $mod+x exec ~/.config/rofi/scripts/powermenu.sh
