# Kısayollar
bindsym $mod+Return exec st 
bindsym $mod+d exec rofi -show drun
bindsym $mod+b exec librewolf
bindsym $mod+Shift+b badwolf
bindsym $mod+v exec copyq show
bindsym $mod+e exec st -n yazi -t "yazi" -e yazi
bindsym $mod+c exec st -n nvim -t "nvim" -e nvim
bindsym $mod+Shift+v exec blueman-manager
bindsym $mod+z exec localsend
bindsym $mod+Shift+s exec steam
bindsym $mod+Shift+d exec discord
bindsym $mod+x exec ~/.config/rofi/scripts/powermenu-i3.sh
bindsym $mod+Shift+e exec thunar
bindsym $mod+j exec ~/.config/rofi/scripts/i3_configs.sh

# $mod + t ile Anlık Saat Bildirimi
bindsym $mod+t exec --no-startup-id ~/.config/i3/scripts/saat.sh
