# Kısayollar
bindsym $mod+Return exec kitty
bindsym $mod+d exec rofi -show drun
bindsym $mod+b exec firefox
bindsym $mod+e exec kitty --name yazi --title yazi yazi
bindsym $mod+c exec kitty --name nvim --title nvim nvim
bindsym $mod+v exec copyq show
bindsym $mod+Shift+v exec blueman-manager
bindsym $mod+z exec localsend
bindsym $mod+Shift+s exec steam
bindsym $mod+Shift+d exec discord
bindsym $mod+x exec ~/.config/rofi/scripts/powermenu-i3-void.sh
bindsym $mod+Shift+e exec thunar
bindsym $mod+j exec ~/.config/rofi/scripts/i3_configs.sh

# $mod + t ile Anlık Saat Bildirimi
bindsym $mod+t exec --no-startup-id ~/.config/i3/scripts/saat.sh
