# Renk Tanimlamalari: <border> <background> <text> <indicator> <child_border>
client.focused          #4a4a4a #0d0d0d #ffffff #6a6a6a #4a4a4a
client.focused_inactive #1a1a1a #0d0d0d #8a8a8a #1a1a1a #1a1a1a
client.unfocused        #0d0d0d #0d0d0d #666666 #0d0d0d #0d0d0d
client.urgent           #A54242 #A54242 #ffffff #A54242 #A54242
client.placeholder      #000000 #0c0c0c #ffffff #000000 #0c0c0c
client.background       #0d0d0d


# Varsayılan pencere kenarlık tarzı (1 piksel ince çizgi, başlık yok)
default_border pixel 1
default_floating_border pixel 1

# Eğer kenarlığı TAMAMEN kaldırmak (0 piksel) istersen üsttekiler yerine bunu yaz:
# default_border pixel 0
# default_floating_border pixel 0

# Tek pencere açıkken kenarlığı otomatik gizle (isteğe bağlı)
hide_edge_borders smart
