# Odaklanma Davranışı
focus_follows_mouse yes

# Masaüstü Atamaları (Assign)
assign [class="^firefox$"] 2
assign [class="^librewolf$"] 2
assign [class="^brave-origin$"] 2
assign [class="^brave-browser$"] 2
assign [class="^discord$"] 6
assign [class="^dev.zed.Zed$"] 5
assign [class="^Spotify$"] 3
#assign [class="(?i)^st"] 1

# Floating (Yüzen) Pencereler
for_window [class="(?i)^pavucontrol$"] floating enable
for_window [class="(?i)^copyq$"] floating enable
for_window [class="(?i)^blueman-manager$"] floating enable
for_window [class="(?i)^localsend"] floating enable

# Yönlendirmeler
#for_window [class="(?i)^thunar$"] move to workspace number 3

# Yazi ve Nvim için yakalama
# NOT: st terminali "st -n yazi" veya "st -n nvim" şeklinde açıldığında
# WM_CLASS (instance) değeri pencere oluşturulduğu an hazır olur.
for_window [class="(?i)^st" instance="^yazi$"] move to workspace number 3
for_window [class="(?i)^st" instance="^nvim$"] move to workspace number 5

# Ncspot scratchpad kuralı config.d/specialws.conf içinde tanımlı (burada tekrar etmiyoruz)
