# Odaklanma Davranışı
focus_follows_mouse yes

# Masaüstü Atamaları (Assign)
assign [class="^firefox$"] 2
assign [class="^librewolf$"] 2
assign [class="^brave-browser$"] 2
assign [class="^discord$"] 6
assign [class="^dev.zed.Zed$"] 5
assign [class="^Spotify$"] 3
assign [class="^kitty$"] 1

# Floating (Yüzen) Pencereler
for_window [class="^org.pulseaudio.pavucontrol$"] floating enable
for_window [class="^com.github.hluk.copyq$"] floating enable
for_window [class="^blueman-manager$"] floating enable
for_window [class="^localsend$"] floating enable
for_window [class="^thunar$"] move to workspace 3

# Ncspot, Yazi ve Nvim için alternatif yakalama
for_window [class="^kitty$" title="^ncspot$"] floating enable, resize set 800 500, move to scratchpad
for_window [class="^kitty$" title="^yazi$"] move to workspace 3
for_window [class="^kitty$" title="^nvim$"] move to workspace 5
