# Ncspot Scratchpad Tanımlaması (Pencere boyutu ve gizleme)
for_window [class="st" title="ncspot"] floating enable, resize set 800 500, move to scratchpad

# Scratchpad Kısayolları
bindsym $mod+a move scratchpad
bindsym $mod+s scratchpad show
