# Ncspot Scratchpad Tanımlaması (Pencere boyutu ve gizleme)
for_window [class="^kitty$" title="^ncspot$"] floating enable, resize set 800 500, move to scratchpad

# Scratchpad Kısayolları
bindsym $mod+m [class="^kitty$" title="^ncspot$"] scratchpad show
bindsym $mod+a move scratchpad
bindsym $mod+s scratchpad show
