# Duvar Kağıdı:wallpaper
exec --no-startup-id feh --bg-fill ~/wallpaper/px.png

# Bar (Polybar)
exec --no-startup-id polybar main

# Bildirim Yöneticisi
exec --no-startup-id dunst

# Pano (Clipboard) Yöneticisi
exec --no-startup-id copyq

# Polkit Yetkilendirme (Void Linux Doğru Dizin Yolu)
#exec --no-startup-id /usr/libexec/polkit-gnome-authentication-agent-1

# Ekran Çözünürlüğü ve Yenileme Hızı
exec --no-startup-id xrandr --output eDP-1 --mode 1920x1080 --rate 60.01 --pos 0x0 --scale 1x1

# Klavye Düzeni ve Hızı
exec --no-startup-id setxkbmap tr
exec --no-startup-id xset r rate 200 35
exec --no-startup-id numlockx on

# Touchpad Ayarları (libinput)
exec --no-startup-id xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
exec --no-startup-id xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
exec --no-startup-id xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Disable While Typing Enabled" 0
